package br.upf.connect_city_api.util.constants.error

import org.springframework.http.HttpStatus

object ErrorStatusConstants {
    val AUTHENTICATION_ERROR_STATUS = HttpStatus.UNAUTHORIZED
    val STORAGE_ERROR_STATUS = HttpStatus.INTERNAL_SERVER_ERROR
    val EMAIL_SEND_ERROR_STATUS = HttpStatus.INTERNAL_SERVER_ERROR
    val INVALID_REQUEST_ERROR_STATUS = HttpStatus.BAD_REQUEST
    val NO_AUTHORIZATION_ERROR_STATUS = HttpStatus.FORBIDDEN
    val PERMISSION_DENIED_ERROR_STATUS = HttpStatus.FORBIDDEN
    val RESOURCE_NOT_FOUND_ERROR_STATUS = HttpStatus.NOT_FOUND
    val TIMEOUT_ERROR_STATUS = HttpStatus.REQUEST_TIMEOUT
    val TOO_MANY_REQUESTS_ERROR_STATUS = HttpStatus.TOO_MANY_REQUESTS
    val VALIDATION_ERROR_STATUS = HttpStatus.BAD_REQUEST
    val JSON_MESSAGE_READ_ERROR_STATUS = HttpStatus.BAD_REQUEST
    val UNEXPECTED_ERROR_STATUS = HttpStatus.INTERNAL_SERVER_ERROR
}
